app/api/urls.py
from django.urls import path, include

from .views import ShortUrlApi
from rest_framework.routers import DefaultRouter


class OptionalSlashDefaulRouter(DefaultRouter):
	def __init__(self):
		super().__init__()
		self.trailing_slash = '/?'


router = OptionalSlashDefaulRouter()
router.register(r'shorturls', ShortUrlApi, basename='x')

urlpatterns = [
	path('', include(router.urls))
]

app/main/urls.py
from django.urls import path, re_path
from .views import HomeView, ShortUrlList, ShortUrlCreate, redirect_to_original_url


urlpatterns = [
	path('', HomeView.as_view(), name='home_view'),
	path('shorturls', ShortUrlList.as_view(), name='shorturl_list_view'),
	path('add', ShortUrlCreate.as_view(), name='shorturl_create_view'),
	re_path(r'^s/(?P<short>.*)', redirect_to_original_url),
]

app/shorteit/urls.py
from django.urls import path, re_path, include


urlpatterns = [
    path('api/v1/', include("api.urls")),
    path('', include("main.urls")),
]

app/api/models.py
from django.db import models

# Create your models here.

app/main/models.py
from django.db import models


class ShortUrl(models.Model):
	"""модель основной таблицы в бд.
	Таблица сокращенных урлов. Содержит сведения о пользователе, оригинальный урл, дату создания, количество переходов
	по короткому урлу и собственно сам сокращенный урл.
	"""
	user_id = models.UUIDField(verbose_name="Идентификатор пользователя")
	original_url = models.URLField(verbose_name="Оригинальный URL")
	short_url = models.URLField(verbose_name="Сокращенный URL", unique=True)
	created_at = models.DateTimeField(verbose_name="Дата создания короткого URL", auto_now_add=True)
	count_click = models.IntegerField(verbose_name="Количество переходов по короткому URL", default=0)

	def __str__(self):
		return f"Short Url: {self.short_url}"

	class Meta:
		db_table = "main_short_url"
		unique_together = ("user_id", "original_url")
		ordering = ('-created_at',)

app/main/forms.py
from django import forms


class ShortUrlCreateForm(forms.Form):
	original_url = forms.CharField(widget=forms.URLInput(attrs={"class": "form-control"}))
	subpart = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}), required=False)

app/api/views.py
import logging

from rest_framework.viewsets import ModelViewSet

from .services import get_queryset_short_url
from .serializers import ShortUrlSerializer


log = logging.getLogger('api_debug')


class ShortUrlApi(ModelViewSet):
	serializer_class = ShortUrlSerializer

	def get_queryset(self):
		return get_queryset_short_url(self.request)

app/main/views.py
import logging
from typing import Callable

from django.views import generic
from django.shortcuts import redirect
from django.contrib import messages
from django.http.request import HttpRequest
from shorteit.settings import PAGINATE_PER_PAGE

from .forms import ShortUrlCreateForm
from .services import (
	create_short_url, get_queryset_short_url, get_original_url, increment_count_links
)

# получаем объект логгера
log = logging.getLogger('debug_log')


class HomeView(generic.TemplateView):
	"""вьюха для главной страницы сайта"""

	template_name = "main/index.html"


class ShortUrlList(generic.ListView):
	"""вьюха для страницы со списком коротких url"""

	context_object_name = 'links'
	template_name = "main/short_url_list.html"
	paginate_by = PAGINATE_PER_PAGE

	def get_queryset(self):
		return get_queryset_short_url(self.request)


class ShortUrlCreate(generic.FormView):
	"""вьюха для страницы создания короткого url"""

	form_class = ShortUrlCreateForm
	template_name = "main/short_url_create.html"

	def post(self, request, *args, **kwargs):
		"""если в переменную success приходит False, то в переменной msg будет описание ошибки
		example: msg = "some error"
		если success=True, то в msg строка об успешной операции
		example: msg = "ok"
		"""

		success, msg = create_short_url(request)
		if not success:
			log.error(f"Ошибка при создании короткого url {msg}")
			messages.error(request, msg)
			return redirect("shorturl_create_view")

		log.debug(f"Короткий url успешно добавлен в бд")
		messages.info(request, msg)
		return redirect("shorturl_list_view")


def redirect_to_original_url(request: HttpRequest, short: str) -> Callable:
	"""фунцкция выполняет редирект на url по его короткому url"""

	url = get_original_url(short)
	if url:
		log.debug(f"Редирект на {url.original_url}")
		increment_count_links(url)
		return redirect(url.original_url)
	else:
		log.warning(f"Запрошенный короткий url c subpart '{short}' не был найден")
		messages.warning(request, "Запрошенный URL не найден. Возможно он уже удален из базы")
		return redirect('shorturl_list_view')

app/main/templates/main/index.html
{% extends "base.html" %}
{% block content %}
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">ShortIt!</h4>
        <p>simple short url application</p>
        <p class="mb-0">2020</p>
    </div>
{% endblock %}

app/main/templates/main/short_url_create.html
{% extends "base.html" %}

{% block content %}

<form action="{% url "shorturl_create_view" %}" method="post">
    {% csrf_token %}
  <div class="form-group">
    {{ form.original_url.errors }}
    <label for="id_original_url">Введите URL адрес, который хотите сократить...</label>
    {{ form.original_url }}
  </div>
   <div class="form-group">
    {{ form.subpart.errors }}
    <label for="id_subpart">Введите текст сокращенного URL(необязательно)...</label>
    {{ form.subpart }}
  </div>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning" role="alert">
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}
    {% endif %}
  <button type="submit" class="btn btn-primary">ShortIt!</button>
</form>
{% endblock %}

app/main/templates/main/short_url_list.html
{%  extends "base.html" %}
{% load tz %}
{% block content %}

    {% if page_obj.has_previous %}
        <a href="{{ page_obj.previous_page_number }}"><<<</a>
        {% else %}
            <<<
    {% endif %}

    {% for num_page in page_obj.paginator.page_range %}
        {% if num_page != page_obj.number %}
            <a href="?page={{ num_page }}">{{ num_page }}</a>
        {% else %}
            {{ num_page }}
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">>>></a>
    {% else %}
            >>>
    {% endif %}


    <table class="table table-striped">
        <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Оригинальный URL</th>
              <th scope="col">Короткий URL</th>
              <th scope="col">Кол. кликов</th>
                <th scope="col">Дата создания</th>
            </tr>
        </thead>
        <tbody>
            {% for link in links %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{{ link.original_url }}">{{ link.original_url | truncatechars:55 }}</a></td>
                <td><a href="{{ link.short_url }}">{{ link.short_url }}</a></td>
                <td>{{ link.count_click }}</td>
              <td>{{ link.created_at  }}</td>
              </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-primary" role="alert">
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}

    {% endif %}
{% endblock %}

app/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <title>short it!</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/main.css" %}">
</head>
<body>
{% include "nav.html" %}
<div class="container">
    {% block content %}

    {% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

app/templates/nav.html
<ul class="nav justify-content-center">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'home_view' %}">Главная</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'shorturl_list_view' %}">Список URL</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'shorturl_create_view' %}">Добавить URL</a>
    </li>
</ul>